version: '3.8'
services:
  simple.airbnb:
    image: simple-airbnb:latest
    container_name: simple-airbnb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - ./.env:/C:\Users\ACHER\pschool\app\.env
